/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OffchainAggregator } from "./OffchainAggregator";
export * as factories from "./factories";
export { OffchainAggregator__factory } from "./factories/OffchainAggregator__factory";
